name: macOS
on:
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/pkgbuild.yml
      - pkgbuild/**
jobs:
  pkgbuild:
    strategy:
      matrix:
        architecture: [x64, aarch64]
    name: pkgbuild
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: brew install --cask packages

    - name: Setup environment variables x64
      uses: allenevans/set-env@v2.0.0
      with:
        MAJOR_VERSION: 8
        FULL_VERSION: 1.8.0_302
        TAG: jdk8u302-b08
        SUB_TAG: 8u302b08
        JVM: hotspot
      if: ${{ matrix.architecture == 'x64' }}

    - name: Setup environment variables aarch64
      uses: allenevans/set-env@v2.0.0
      with:
        MAJOR_VERSION: 17
        FULL_VERSION: 17.0.1_12
        TAG: jdk-17.0.1+12
        SUB_TAG: 17.0.1_12
        JVM: hotspot
      if: ${{ matrix.architecture == 'aarch64' }}

    - name: Download prebuilt binaries
      run: |
        mkdir -p workspace/target/
        cd workspace/target/
        wget -q "https://github.com/adoptium/temurin${{ env.MAJOR_VERSION }}-binaries/releases/download/${{ env.TAG }}/OpenJDK${{ env.MAJOR_VERSION }}U-jdk_${{ matrix.architecture }}_mac_${{ env.JVM }}_${{ env.SUB_TAG }}.tar.gz"

    - name: Download prebuilt binaries
      run: |
        wget -q "https://github.com/adoptium/temurin${{ env.MAJOR_VERSION }}-binaries/releases/download/${{ env.TAG }}/OpenJDK${{ env.MAJOR_VERSION }}U-jre_${{ matrix.architecture }}_mac_${{ env.JVM }}_${{ env.SUB_TAG }}.tar.gz"
      if: ${{ matrix.architecture == 'x64' }}

    - name: Create Package
      run: |
        export WORKSPACE=$PWD
        bash pkgbuild/create-installer-mac.sh
        
    - uses: actions/upload-artifact@v3
      with:
        name: macOS_${{ matrix.architecture }}
        path: workspace/target/*.pkg
