name: macOS
on:
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/pkgbuild.yml
      - pkgbuild/**
jobs:
  pkgbuild:
    strategy:
      matrix:
        architecture: [x64, aarch64]
    name: pkgbuild
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - name: Install dependencies
      run: brew install --cask packages

    - name: Setup environment variables
      uses: allenevans/set-env@0f3306034af0ea21dd28983b6e7c1614ee317739 # v3.0.0
      with:
        MAJOR_VERSION: 17
        FULL_VERSION: 17.0.3_7
        TAG: jdk-17.0.3+7
        SUB_TAG: 17.0.3_7
        JVM: hotspot

    - name: Download prebuilt binaries
      run: |
        mkdir -p workspace/target/
        cd workspace/target/
        wget -q "https://github.com/adoptium/temurin${{ env.MAJOR_VERSION }}-binaries/releases/download/${{ env.TAG }}/OpenJDK${{ env.MAJOR_VERSION }}U-jdk_${{ matrix.architecture }}_mac_${{ env.JVM }}_${{ env.SUB_TAG }}.tar.gz"

    - name: Create Package
      run: |
        export WORKSPACE=$PWD
        bash pkgbuild/create-installer-mac.sh

    - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: macOS_${{ matrix.architecture }}
        path: workspace/target/*.pkg
